### ISSUE TITLE
Colors!

### ISSUE THREAD

**Issue by jish** [mwerner/timekit#12]
See what you're missing out on @shajith ? ;)

![colors](https://cloud.githubusercontent.com/assets/1817/6648266/1ece619e-c995-11e4-86b9-41a5645b01ec.gif)

cc: @mwerner @littlemisosoup

**Comment by littlemisosoup** [comment]
Holy crap guys you're killing it!

**Comment by shajith** [comment]
Brb talking to VCs

**Comment by mwerner** [comment]
:moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag:
